version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - NEXT_PUBLIC_CONNECTIONS_API_HOST=backend:8000
    depends_on:
      - backend
    networks:
      - connections-network

  # Placeholder for your backend service
  # You can uncomment and modify this if you want to run both services together
  # backend:
  #   image: your-backend-image:latest
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - connections-network

networks:
  connections-network:
    driver: bridge
